### ISSUE TITLE
clear button  can not use

### ISSUE THREAD

**Issue by zhouxs1023** [cbarbat/eigenmath1337#1]
clear button  can not clear history

**Comment by cbarbat** [comment]
The clear button just executes the command "clear" in eigenmath.
It clears the user defined symbols, not the screen or the history.
If you want that, you can try to implement it yourself.

**Comment by zhouxs1023** [comment]
I used this project that cpnpiled eigenmath1337.exe run as below:
running help menu would turn on  "clear"
![eigenmath1337](https://user-images.githubusercontent.com/905931/73383744-e5a5cd00-4304-11ea-87ec-3a36dfb3a7bb.gif)
I used eigenmath137.exe that is comed from internet as below:
running help menu do not turn on  "clear" and clear button may clear up cmd history
![eigenmath137](https://user-images.githubusercontent.com/905931/73383780-f3f3e900-4304-11ea-97af-2c8f155bb7fd.gif)

**Comment by cbarbat** [comment]
Well, I don't have the source for eigenmath137... If you find it somewhere, you can compare to my version and see why it is behaving differently.

**Comment by zhouxs1023** [comment]
Thank your,I see source

**Comment by cbarbat** [comment]
You can call routine "clear_term()" from "eval_clear()".
This should solve your question.

**Comment by cbarbat** [comment]
See commit 4b530419cfa8b3f3b5bbc91f932230b24a1438d1
