### ISSUE TITLE
Is there a plan to develop a new math editor?

### ISSUE THREAD

**Issue by zhouxs1023** [cbarbat/eigenmath1337#2]
Is there a plan to develop a new math editor ? it may use imgui QT C# to develop a modern UI, similar to Maple,maxima, etc., and it's better to have a  change skin theme？

**Comment by cbarbat** [comment]
I suggested this to George Weigt, the author of Eigenmath.
He found this to be a good idea, but has no time currently to implement it.
Can you maybe start work on it? Look at src/windows for the Windows GUI code and maybe you can translate that to the Qt Toolkit?

**Comment by zhouxs1023** [comment]
I am more interested in mathematics and have no experience for UI development, so I hope to have a good math studio!
